---
go_url: "https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz"
go_exp_url: https://github.com/justwatchcom/elasticsearch_exporter/releases/download/v1.0.0/elasticsearch_exporter-1.0.0.linux-amd64.tar.gz
sysd_script: "/usr/lib/systemd/system/elasticsearch_exporter.service"